version: '3.9'
services:
  hipush:
    container_name: hipush
    platform: linux/amd64
    image: hub.hitosea.com/cossim/hipush
    volumes:
      - ./config.yaml:/config/config.yaml
      # 如果启用了ios推送，需要将推送证书挂载到容器中
      #- ./AuthKey_xxx.p8:/config/key/AuthKey_xxx.p8
    command: -config /config/config.yaml
    ports:
      - "7070:7070"
      - "7071:7071"