

ios:
  - enabled: true
    # 应用程序的 Bundle ID
    # ios capacitor.config文件中的appId 例如com.hitosea.apptest
    appid: com.hitosea.apptest
    # APNs 密钥文件路径
    key_path: ""
    # 密钥类型（例如：pem）
    key_type: pem
    # 密钥文件的密码（如果有）
    password: ""
    # 是否为生产环境
    production: false
    # 最大并发推送数
    max_concurrent_pushes: 100
    # 最大重试次数
    max_retry: 5
    # 密钥 ID
    key_id: ""
    # 开发团队 ID
    team_id: ""
  - enabled: true
    appid: ""
    key_path: ""
    key_type: pem
    password: ""
    production: false
    max_concurrent_pushes: 100
    max_retry: 0
    key_id: ""
    team_id: ""
huawei:
  - enabled: true
    appid: huawei-appid-1
    appsecret: huawei-app-secret-1
    max_retry: 5
